[Preferences]
WebUI\Address=*
WebUI\Password_PBKDF2="@ByteArray(YXV0by1iYW5ndW1pLXNhbA==:I1QozK7rFTwrsqgQC3bcZdCFSDi4h2lu+mReHz7fPa++Whd73lKo+lxsbR9W0R9E+6stXlzMzqB2iA06bvHbxg==)"
WebUI\Port=8080
WebUI\ServerDomains=*
WebUI\Username=admin
