services:
  download:
    build:
      context: .
      dockerfile: Dockerfile.download
    volumes:
      - ./config/config.yaml:/usr/src/app/config/config.yaml
      - ./db:/usr/src/app/db
    restart: on-failure
