FROM node:22-alpine AS builder

WORKDIR /usr/src/app

# Install dependencies first to cache them
COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm npm clean-install

# Copy the rest of the code
COPY . .

RUN --mount=type=cache,target=/root/.npm npm run build

FROM node:22-alpine AS runner

WORKDIR /usr/src/app

# Copy only the necessary files
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist

CMD ["npm", "run", "download-task"]
