seasons:
  - rss: https://mikanani.me/RSS/Bangumi?bangumiId=3560&subgroupid=370
    title: Ore dake Level Up na Ken
    seasonNumber: 1
    alias:
      - 我独自升级 -起于暗影

  - rss: https://mikanani.me/RSS/Bangumi?bangumiId=3518&subgroupid=583
    title: BanG Dream! Ave Mujica
    seasonNumber: 1

  - rss: https://mikanani.me/RSS/Bangumi?bangumiId=3488&subgroupid=597
    title: Chi. Chikyuu no Undou ni Tsuite
    seasonNumber: 1
    alias:
      - 地。—关于地球的运动—
    match:
      title:
        - 繁日内嵌
        - 1080p

  - rss: https://mikanani.me/RSS/Bangumi?bangumiId=3436&subgroupid=583
    title: Dan Da Dan
    seasonNumber: 1
    alias:
      - 胆大党

  - rss: https://mikanani.me/RSS/Bangumi?bangumiId=3454&subgroupid=370
    title: Maou 2099
    seasonNumber: 1
    alias:
      - 魔王 2099

  - rss: https://mikanani.me/RSS/Bangumi?bangumiId=3439&subgroupid=42
    title: Natsume Yuujinchou Shichi
    seasonNumber: 7
    alias:
      - 夏目友人帐 七
    match:
      title:
        - '简日双语字幕'

download:
  path: /downloads
  qBittorrent:
    host: host.docker.internal
    port: 5001
    username: admin
    password: adminadmin
    ssl: false

move:
  root: E:\Bangumi
