/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSeasonsRouteImport } from './routes/api/seasons'
import { Route as ApiDownloadsRouteImport } from './routes/api/downloads'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiSeasonsRssRouteImport } from './routes/api/seasons.$rss'
import { Route as ApiRssRefreshRouteImport } from './routes/api/rss/refresh'
import { Route as ApiMikanSearchRouteImport } from './routes/api/mikan/search'
import { Route as ApiMikanBangumiIdRouteImport } from './routes/api/mikan/bangumi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeasonsRoute = ApiSeasonsRouteImport.update({
  id: '/api/seasons',
  path: '/api/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadsRoute = ApiDownloadsRouteImport.update({
  id: '/api/downloads',
  path: '/api/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeasonsRssRoute = ApiSeasonsRssRouteImport.update({
  id: '/$rss',
  path: '/$rss',
  getParentRoute: () => ApiSeasonsRoute,
} as any)
const ApiRssRefreshRoute = ApiRssRefreshRouteImport.update({
  id: '/api/rss/refresh',
  path: '/api/rss/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMikanSearchRoute = ApiMikanSearchRouteImport.update({
  id: '/api/mikan/search',
  path: '/api/mikan/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMikanBangumiIdRoute = ApiMikanBangumiIdRouteImport.update({
  id: '/api/mikan/bangumi/$id',
  path: '/api/mikan/bangumi/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/seasons': typeof ApiSeasonsRouteWithChildren
  '/api/mikan/search': typeof ApiMikanSearchRoute
  '/api/rss/refresh': typeof ApiRssRefreshRoute
  '/api/seasons/$rss': typeof ApiSeasonsRssRoute
  '/api/mikan/bangumi/$id': typeof ApiMikanBangumiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/seasons': typeof ApiSeasonsRouteWithChildren
  '/api/mikan/search': typeof ApiMikanSearchRoute
  '/api/rss/refresh': typeof ApiRssRefreshRoute
  '/api/seasons/$rss': typeof ApiSeasonsRssRoute
  '/api/mikan/bangumi/$id': typeof ApiMikanBangumiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/seasons': typeof ApiSeasonsRouteWithChildren
  '/api/mikan/search': typeof ApiMikanSearchRoute
  '/api/rss/refresh': typeof ApiRssRefreshRoute
  '/api/seasons/$rss': typeof ApiSeasonsRssRoute
  '/api/mikan/bangumi/$id': typeof ApiMikanBangumiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/config'
    | '/api/downloads'
    | '/api/seasons'
    | '/api/mikan/search'
    | '/api/rss/refresh'
    | '/api/seasons/$rss'
    | '/api/mikan/bangumi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/config'
    | '/api/downloads'
    | '/api/seasons'
    | '/api/mikan/search'
    | '/api/rss/refresh'
    | '/api/seasons/$rss'
    | '/api/mikan/bangumi/$id'
  id:
    | '__root__'
    | '/'
    | '/api/config'
    | '/api/downloads'
    | '/api/seasons'
    | '/api/mikan/search'
    | '/api/rss/refresh'
    | '/api/seasons/$rss'
    | '/api/mikan/bangumi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiDownloadsRoute: typeof ApiDownloadsRoute
  ApiSeasonsRoute: typeof ApiSeasonsRouteWithChildren
  ApiMikanSearchRoute: typeof ApiMikanSearchRoute
  ApiRssRefreshRoute: typeof ApiRssRefreshRoute
  ApiMikanBangumiIdRoute: typeof ApiMikanBangumiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seasons': {
      id: '/api/seasons'
      path: '/api/seasons'
      fullPath: '/api/seasons'
      preLoaderRoute: typeof ApiSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloads': {
      id: '/api/downloads'
      path: '/api/downloads'
      fullPath: '/api/downloads'
      preLoaderRoute: typeof ApiDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seasons/$rss': {
      id: '/api/seasons/$rss'
      path: '/$rss'
      fullPath: '/api/seasons/$rss'
      preLoaderRoute: typeof ApiSeasonsRssRouteImport
      parentRoute: typeof ApiSeasonsRoute
    }
    '/api/rss/refresh': {
      id: '/api/rss/refresh'
      path: '/api/rss/refresh'
      fullPath: '/api/rss/refresh'
      preLoaderRoute: typeof ApiRssRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mikan/search': {
      id: '/api/mikan/search'
      path: '/api/mikan/search'
      fullPath: '/api/mikan/search'
      preLoaderRoute: typeof ApiMikanSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mikan/bangumi/$id': {
      id: '/api/mikan/bangumi/$id'
      path: '/api/mikan/bangumi/$id'
      fullPath: '/api/mikan/bangumi/$id'
      preLoaderRoute: typeof ApiMikanBangumiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiSeasonsRouteChildren {
  ApiSeasonsRssRoute: typeof ApiSeasonsRssRoute
}

const ApiSeasonsRouteChildren: ApiSeasonsRouteChildren = {
  ApiSeasonsRssRoute: ApiSeasonsRssRoute,
}

const ApiSeasonsRouteWithChildren = ApiSeasonsRoute._addFileChildren(
  ApiSeasonsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiDownloadsRoute: ApiDownloadsRoute,
  ApiSeasonsRoute: ApiSeasonsRouteWithChildren,
  ApiMikanSearchRoute: ApiMikanSearchRoute,
  ApiRssRefreshRoute: ApiRssRefreshRoute,
  ApiMikanBangumiIdRoute: ApiMikanBangumiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
