/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSeasonsRouteImport } from './routes/api/seasons'
import { Route as ApiDownloadsRouteImport } from './routes/api/downloads'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiRssRefreshRouteImport } from './routes/api/rss/refresh'
import { Route as ApiMoverJobsRouteImport } from './routes/api/mover/jobs'
import { Route as ApiMikanSearchRouteImport } from './routes/api/mikan/search'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiMoverJobsClaimRouteImport } from './routes/api/mover/jobs/claim'
import { Route as ApiMikanBangumiIdRouteImport } from './routes/api/mikan/bangumi.$id'
import { Route as ApiMoverJobsHashSourceRouteImport } from './routes/api/mover/jobs/$hash/source'
import { Route as ApiMoverJobsHashFailRouteImport } from './routes/api/mover/jobs/$hash/fail'
import { Route as ApiMoverJobsHashCompleteRouteImport } from './routes/api/mover/jobs/$hash/complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeasonsRoute = ApiSeasonsRouteImport.update({
  id: '/api/seasons',
  path: '/api/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadsRoute = ApiDownloadsRouteImport.update({
  id: '/api/downloads',
  path: '/api/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRssRefreshRoute = ApiRssRefreshRouteImport.update({
  id: '/api/rss/refresh',
  path: '/api/rss/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoverJobsRoute = ApiMoverJobsRouteImport.update({
  id: '/api/mover/jobs',
  path: '/api/mover/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMikanSearchRoute = ApiMikanSearchRouteImport.update({
  id: '/api/mikan/search',
  path: '/api/mikan/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoverJobsClaimRoute = ApiMoverJobsClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => ApiMoverJobsRoute,
} as any)
const ApiMikanBangumiIdRoute = ApiMikanBangumiIdRouteImport.update({
  id: '/api/mikan/bangumi/$id',
  path: '/api/mikan/bangumi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoverJobsHashSourceRoute = ApiMoverJobsHashSourceRouteImport.update({
  id: '/$hash/source',
  path: '/$hash/source',
  getParentRoute: () => ApiMoverJobsRoute,
} as any)
const ApiMoverJobsHashFailRoute = ApiMoverJobsHashFailRouteImport.update({
  id: '/$hash/fail',
  path: '/$hash/fail',
  getParentRoute: () => ApiMoverJobsRoute,
} as any)
const ApiMoverJobsHashCompleteRoute =
  ApiMoverJobsHashCompleteRouteImport.update({
    id: '/$hash/complete',
    path: '/$hash/complete',
    getParentRoute: () => ApiMoverJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/seasons': typeof ApiSeasonsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/mikan/search': typeof ApiMikanSearchRoute
  '/api/mover/jobs': typeof ApiMoverJobsRouteWithChildren
  '/api/rss/refresh': typeof ApiRssRefreshRoute
  '/api/mikan/bangumi/$id': typeof ApiMikanBangumiIdRoute
  '/api/mover/jobs/claim': typeof ApiMoverJobsClaimRoute
  '/api/mover/jobs/$hash/complete': typeof ApiMoverJobsHashCompleteRoute
  '/api/mover/jobs/$hash/fail': typeof ApiMoverJobsHashFailRoute
  '/api/mover/jobs/$hash/source': typeof ApiMoverJobsHashSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/seasons': typeof ApiSeasonsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/mikan/search': typeof ApiMikanSearchRoute
  '/api/mover/jobs': typeof ApiMoverJobsRouteWithChildren
  '/api/rss/refresh': typeof ApiRssRefreshRoute
  '/api/mikan/bangumi/$id': typeof ApiMikanBangumiIdRoute
  '/api/mover/jobs/claim': typeof ApiMoverJobsClaimRoute
  '/api/mover/jobs/$hash/complete': typeof ApiMoverJobsHashCompleteRoute
  '/api/mover/jobs/$hash/fail': typeof ApiMoverJobsHashFailRoute
  '/api/mover/jobs/$hash/source': typeof ApiMoverJobsHashSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/config': typeof ApiConfigRoute
  '/api/downloads': typeof ApiDownloadsRoute
  '/api/seasons': typeof ApiSeasonsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/mikan/search': typeof ApiMikanSearchRoute
  '/api/mover/jobs': typeof ApiMoverJobsRouteWithChildren
  '/api/rss/refresh': typeof ApiRssRefreshRoute
  '/api/mikan/bangumi/$id': typeof ApiMikanBangumiIdRoute
  '/api/mover/jobs/claim': typeof ApiMoverJobsClaimRoute
  '/api/mover/jobs/$hash/complete': typeof ApiMoverJobsHashCompleteRoute
  '/api/mover/jobs/$hash/fail': typeof ApiMoverJobsHashFailRoute
  '/api/mover/jobs/$hash/source': typeof ApiMoverJobsHashSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/config'
    | '/api/downloads'
    | '/api/seasons'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/mikan/search'
    | '/api/mover/jobs'
    | '/api/rss/refresh'
    | '/api/mikan/bangumi/$id'
    | '/api/mover/jobs/claim'
    | '/api/mover/jobs/$hash/complete'
    | '/api/mover/jobs/$hash/fail'
    | '/api/mover/jobs/$hash/source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/config'
    | '/api/downloads'
    | '/api/seasons'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/mikan/search'
    | '/api/mover/jobs'
    | '/api/rss/refresh'
    | '/api/mikan/bangumi/$id'
    | '/api/mover/jobs/claim'
    | '/api/mover/jobs/$hash/complete'
    | '/api/mover/jobs/$hash/fail'
    | '/api/mover/jobs/$hash/source'
  id:
    | '__root__'
    | '/'
    | '/api/config'
    | '/api/downloads'
    | '/api/seasons'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/api/mikan/search'
    | '/api/mover/jobs'
    | '/api/rss/refresh'
    | '/api/mikan/bangumi/$id'
    | '/api/mover/jobs/claim'
    | '/api/mover/jobs/$hash/complete'
    | '/api/mover/jobs/$hash/fail'
    | '/api/mover/jobs/$hash/source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiDownloadsRoute: typeof ApiDownloadsRoute
  ApiSeasonsRoute: typeof ApiSeasonsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiMikanSearchRoute: typeof ApiMikanSearchRoute
  ApiMoverJobsRoute: typeof ApiMoverJobsRouteWithChildren
  ApiRssRefreshRoute: typeof ApiRssRefreshRoute
  ApiMikanBangumiIdRoute: typeof ApiMikanBangumiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seasons': {
      id: '/api/seasons'
      path: '/api/seasons'
      fullPath: '/api/seasons'
      preLoaderRoute: typeof ApiSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloads': {
      id: '/api/downloads'
      path: '/api/downloads'
      fullPath: '/api/downloads'
      preLoaderRoute: typeof ApiDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rss/refresh': {
      id: '/api/rss/refresh'
      path: '/api/rss/refresh'
      fullPath: '/api/rss/refresh'
      preLoaderRoute: typeof ApiRssRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mover/jobs': {
      id: '/api/mover/jobs'
      path: '/api/mover/jobs'
      fullPath: '/api/mover/jobs'
      preLoaderRoute: typeof ApiMoverJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mikan/search': {
      id: '/api/mikan/search'
      path: '/api/mikan/search'
      fullPath: '/api/mikan/search'
      preLoaderRoute: typeof ApiMikanSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mover/jobs/claim': {
      id: '/api/mover/jobs/claim'
      path: '/claim'
      fullPath: '/api/mover/jobs/claim'
      preLoaderRoute: typeof ApiMoverJobsClaimRouteImport
      parentRoute: typeof ApiMoverJobsRoute
    }
    '/api/mikan/bangumi/$id': {
      id: '/api/mikan/bangumi/$id'
      path: '/api/mikan/bangumi/$id'
      fullPath: '/api/mikan/bangumi/$id'
      preLoaderRoute: typeof ApiMikanBangumiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mover/jobs/$hash/source': {
      id: '/api/mover/jobs/$hash/source'
      path: '/$hash/source'
      fullPath: '/api/mover/jobs/$hash/source'
      preLoaderRoute: typeof ApiMoverJobsHashSourceRouteImport
      parentRoute: typeof ApiMoverJobsRoute
    }
    '/api/mover/jobs/$hash/fail': {
      id: '/api/mover/jobs/$hash/fail'
      path: '/$hash/fail'
      fullPath: '/api/mover/jobs/$hash/fail'
      preLoaderRoute: typeof ApiMoverJobsHashFailRouteImport
      parentRoute: typeof ApiMoverJobsRoute
    }
    '/api/mover/jobs/$hash/complete': {
      id: '/api/mover/jobs/$hash/complete'
      path: '/$hash/complete'
      fullPath: '/api/mover/jobs/$hash/complete'
      preLoaderRoute: typeof ApiMoverJobsHashCompleteRouteImport
      parentRoute: typeof ApiMoverJobsRoute
    }
  }
}

interface ApiMoverJobsRouteChildren {
  ApiMoverJobsClaimRoute: typeof ApiMoverJobsClaimRoute
  ApiMoverJobsHashCompleteRoute: typeof ApiMoverJobsHashCompleteRoute
  ApiMoverJobsHashFailRoute: typeof ApiMoverJobsHashFailRoute
  ApiMoverJobsHashSourceRoute: typeof ApiMoverJobsHashSourceRoute
}

const ApiMoverJobsRouteChildren: ApiMoverJobsRouteChildren = {
  ApiMoverJobsClaimRoute: ApiMoverJobsClaimRoute,
  ApiMoverJobsHashCompleteRoute: ApiMoverJobsHashCompleteRoute,
  ApiMoverJobsHashFailRoute: ApiMoverJobsHashFailRoute,
  ApiMoverJobsHashSourceRoute: ApiMoverJobsHashSourceRoute,
}

const ApiMoverJobsRouteWithChildren = ApiMoverJobsRoute._addFileChildren(
  ApiMoverJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiDownloadsRoute: ApiDownloadsRoute,
  ApiSeasonsRoute: ApiSeasonsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiMikanSearchRoute: ApiMikanSearchRoute,
  ApiMoverJobsRoute: ApiMoverJobsRouteWithChildren,
  ApiRssRefreshRoute: ApiRssRefreshRoute,
  ApiMikanBangumiIdRoute: ApiMikanBangumiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
